db = sqlite('geo.db');

% Insert into series - FIX: Use sqlwrite or prepared statement format
data_series = table({'GSE133694'}, ...
    {'The role of chromatin regulators in chromatin organization and gene expression'}, ...
    {'We used an assay for globally mapping chromatin accessibility and regulatory elements in mouse liver tissue, seeking to assess the contributions of chromatin regulators...'}, ...
    {'Mus musculus'}, ...
    {'Expression profiling by high throughput sequencing'}, ...
    {'2019-06-13'}, ...
    'VariableNames', {'accession', 'title', 'summary', 'organism', 'experiment_type', 'submission_date'});

sqlwrite(db, 'series', data_series);

% Insert into samples - FIX: Use sqlwrite or prepared statement format
data_samples = table({'GSM3896128'}, ...
    {'GSE133694'}, ...
    {'WT_1'}, ...
    {'Mus musculus'}, ...
    {'genotype: wild type; tissue: liver'}, ...
    {'liver tissue'}, ...
    'VariableNames', {'gsm_accession', 'gse_accession', 'title', 'organism', 'characteristics', 'source_name'});

sqlwrite(db, 'samples', data_samples);

